name: example-workflow
on: [push]
jobs:
  hello:
    if: github.repository == 'Mr-siva/project_poc'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello Siva,"
        run:  echo "Hello This is your repository."
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: "Bye Siva"
        run:  echo "This is not your repo"