# comments are added here
name: "Context needs"
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: ['push']

jobs:
  jobsB:
    runs-on: ubuntu-latest
    needs: jobsA
    steps:
      - name: This is step B
        run: echo "World"
  jobsA:
    runs-on: ubuntu-latest
    steps:
      - name: This is step A
        run: echo "Hello"
      

    
  