# comments are added here
name: "Context needs"

on: ['push']

jobs:
  jobsB:
    runs-on: ununtu-latest
    
    steps:
      - name: This is step B
        run: echo "World"
  jobsA:
    runs-on: ununtu-latest
    steps:
      - name: This is step A
        run: echo "Hello"
      

    
  